/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

// RCC AHB1ENR Register (0x40023800 + 0x30)
#define RCC_AHB1ENR_t    ((volatile RCC_AHB1ENR * const)(0x40023800 + 0x30))

// GPIOA MODER Register (0x40020000)
#define GPIOA_MODER_t    ((volatile GPIOx_MODER * const)(0x40020000 + 0x00))

// GPIOD MODER Register (0x40020C00)
#define GPIOD_MODER_t    ((volatile GPIOx_MODER * const)(0x40020C00 +0x00))

// GPIOD ODR Register (0x40020C00 + 0x14)
#define GPIOD_ODR_t      ((volatile GPIOx_ODR   * const)(0x40020C00 + 0x14))


int main(void)
{
	RCC_AHB1ENR_t->GPIODEN |= 1;

	GPIOD_MODER_t->MODER12 = 0x01;


	while (1)
	    {
			GPIOD_ODR_t->ODR12 ^= 1;
	        for (volatile int i = 0; i < 1000000; i++);  // crude delay
	    }
}
