/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    // -------------------------
    // RCC Clock Enable
    // -------------------------
    uint32_t volatile *const pClkCtrlReg = (uint32_t*)0x40023830;  // RCC AHB1ENR
    *pClkCtrlReg |= (1 << 3);  // Enable clock for GPIOD
    *pClkCtrlReg |= (1 << 0);  // Enable clock for GPIOA

    // -------------------------
    // GPIO Register Addresses
    // -------------------------
    uint32_t volatile *const pPortDModeReg = (uint32_t*)0x40020C00;   // GPIOD MODER
    uint32_t volatile *const pPortDOutReg  = (uint32_t*)0x40020C14;   // GPIOD ODR
    uint32_t volatile *const pPortAModeReg = (uint32_t*)0x40020000;   // GPIOA MODER
    uint32_t const volatile *pPortAIdReg   = (uint32_t*)0x40020010;   // GPIOA IDR

    // -------------------------
    // Configure PD12 as Output
    // -------------------------
    *pPortDModeReg &= ~(0x3 << 24);  // Clear MODER bits for PD12
    *pPortDModeReg |=  (0x1 << 24);  // Set PD12 as output

    // -------------------------
    // Configure PA0 as Input
    // -------------------------
    *pPortAModeReg &= ~(0x3 << 0);   // Clear MODER bits for PA0 (input mode)

    // -------------------------
    // Main Loop
    // -------------------------
    while (1)
    {
        uint8_t pinStatus = (uint8_t)(*pPortAIdReg & 0x01);  // Read PA0 input

        if (pinStatus)
        {
            *pPortDOutReg |= (1 << 12);   // Set PD12 high (LED ON)
        }
        else
        {
            *pPortDOutReg &= ~(1 << 12);  // Set PD12 low (LED OFF)
        }
    }
}
