/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



int main(void)
{
    // -------------------------
    // RCC Clock Enable for GPIO A
    // -------------------------
    uint32_t volatile *const RCC_AHB1ENR = (uint32_t*)(0x40023800 + 0x30);  // RCC AHB1ENR
    *RCC_AHB1ENR |= (1 << 0);  // Enable clock for GPIOA

    // -------------------------
    // GPIO Register address
    // -------------------------
    uint32_t volatile *const GPIOA_MODER = (uint32_t*)0x40020000; //GPIOA MODER
    *GPIOA_MODER &= ~(0x03 << (8*2));
    *GPIOA_MODER |= (0x2 << (8*2)); ///setting this PA8 as alternate function
    // -------------------------------------


    //-------------------------------------------------------
    // GPIOA_AFHR making the alternate function to af0

    uint32_t volatile *const GPIOA_AFRH = (uint32_t*)(0x40020000 + 0x24); ///finding the address
    *GPIOA_AFRH &= ~(0xf << 0) ; //	making all bits clear AF0 = 00000

    //-------------------------------------------------------

    //-----------------
    //Configure the rcc register for the mco1
    //---------------
    uint32_t volatile *const RCC_CFGR = (uint32_t*)( 0x40023800 + 0x08);
    *RCC_CFGR &= ~(0x03 << 21);
    *RCC_CFGR &= ~(0x7 << 24);
    *RCC_CFGR |= (0x7 << 24);

	for(;;);
}


void I2C3_EV_IRQHandler(void)
{

}
