/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{

	uint32_t volatile *pClkCtrlReg = (uint32_t*)0x40023830; // address of clock control register
	uint32_t volatile *pPortDModeReg = (uint32_t*)0x40020C00; //address of gpio mode register
	uint32_t volatile *pPortDOutReg = (uint32_t*)0x40020C14; // adress of port data direction register

	// enable the clock register for the off rcc_AHB1 bus bit 3 for the GPIO port D
	*pClkCtrlReg |= *pClkCtrlReg | (1<<3);

	//configure mode of the i/o pin as output
	//clear the bit 24 and 25
	*pPortDModeReg &= ~(0x3 << 24);

	//set the bit 24
	*pPortDModeReg |= (1 << 24);


	//now turn on the led connected to PD12 pin high by GPIOD_ODR register
	while (1)
	    {
	        *pPortDOutReg ^= (1 << 12);  // XOR bit 12 to toggle
	        for (volatile int i = 0; i < 1000000; i++);  // crude delay
	    }
		/* Loop forever */

}
