/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>

int main(void)
{
	printf("Hello World\n");
	printf("size char %u\n",sizeof(char));
	printf("size short %u\n",sizeof(short));
	printf("size int %u\n",sizeof(int));
	printf("size long %u\n",sizeof(long));
	printf("size long long %u\n",sizeof(long long));
	printf("size double %u\n",sizeof(double));
	printf("size float %u\n",sizeof(float));

    /* Loop forever */
	for(;;);
}
